/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zxw_coco_Sprite */

#ifndef _Included_com_zxw_coco_Sprite
#define _Included_com_zxw_coco_Sprite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zxw_coco_Sprite
 * Method:    getResult
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zxw_coco_Sprite_getResult
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
